In [ ]:
# Hadi Hassan
# EPPS 6317
# Midterm Project
# Part 2/3 - Alumni Research

In [1]:
# Import pandas and CSV files. We will first inspect 
import pandas as pd

alumni_data = pd.read_csv("alumni_data.csv")
income_debt_data = pd.read_csv("income_debt_data.csv")

# Inspect data
display(alumni_data.head())
display(alumni_data.info())
display(income_debt_data.info())
display(income_debt_data.head())

,8f9158c3-1496-422d-b7d4-9a2917036850,23,male,Psychology,James Whitaker
0,4e43daa8-3428-46be-a58f-63c1f7a0b630,26,male,Mathematics,Daniel Okafor
1,c18438e9-28b0-40fa-a7fb-ac978e8289b2,24,male,Psychology,Marcus Delgado
2,dba2fa25-af64-480e-afa3-3ba82ec38f9e,30,male,Engineering,Ethan Brooks
3,6d8393b6-e937-4889-b40a-ebcfa521db4f,28,male,Computer Science,Raj Patel
4,5889caa0-193d-4064-bc3e-79aaf8d66ecc,23,male,Mathematics,Lucas Moreau

<class 'pandas.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 5 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   8f9158c3-1496-422d-b7d4-9a2917036850  49 non-null     str
 1   23                                    49 non-null     int64
 2   male                                  49 non-null     str
 3   Psychology                            49 non-null     str
 4   James Whitaker                        49 non-null     str
dtypes: int64(1), str(4)
memory usage: 2.0 KB

None

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 50 non-null     str
 1   Income             50 non-null     int64
 2   Student Loan Debt  50 non-null     int64
dtypes: int64(2), str(1)
memory usage: 1.3 KB

None

                                     ID  Income  Student Loan Debt
0  8f9158c3-1496-422d-b7d4-9a2917036850   69117              46874
1  4e43daa8-3428-46be-a58f-63c1f7a0b630   96540              44909
2  c18438e9-28b0-40fa-a7fb-ac978e8289b2   56071              15016
3  dba2fa25-af64-480e-afa3-3ba82ec38f9e   79009              15587
4  6d8393b6-e937-4889-b40a-ebcfa521db4f   99514               5037

In [2]:
# Read CSV without treating the first row as column names
test_data = pd.read_csv("alumni_data.csv", header=None)

test_data.head()

,0,1,2,3,4
0,8f9158c3-1496-422d-b7d4-9a2917036850,23,male,Psychology,James Whitaker
1,4e43daa8-3428-46be-a58f-63c1f7a0b630,26,male,Mathematics,Daniel Okafor
2,c18438e9-28b0-40fa-a7fb-ac978e8289b2,24,male,Psychology,Marcus Delgado
3,dba2fa25-af64-480e-afa3-3ba82ec38f9e,30,male,Engineering,Ethan Brooks
4,6d8393b6-e937-4889-b40a-ebcfa521db4f,28,male,Computer Science,Raj Patel

In [3]:
# Since the alumni data CSV file has no header names, we will give it ourselves
column_names = ["id", "age", "gender", "major", "name"]

alumni_data = pd.read_csv(
    "alumni_data.csv",
    names=column_names)
# Inspect all again after adding header titles
display(alumni_data.info())
display(alumni_data.head())
display(income_debt_data.info())
display(income_debt_data.head())

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      50 non-null     str
 1   age     50 non-null     int64
 2   gender  50 non-null     str
 3   major   50 non-null     str
 4   name    50 non-null     str
dtypes: int64(1), str(4)
memory usage: 2.1 KB

None

,id,age,gender,major,name
0,8f9158c3-1496-422d-b7d4-9a2917036850,23,male,Psychology,James Whitaker
1,4e43daa8-3428-46be-a58f-63c1f7a0b630,26,male,Mathematics,Daniel Okafor
2,c18438e9-28b0-40fa-a7fb-ac978e8289b2,24,male,Psychology,Marcus Delgado
3,dba2fa25-af64-480e-afa3-3ba82ec38f9e,30,male,Engineering,Ethan Brooks
4,6d8393b6-e937-4889-b40a-ebcfa521db4f,28,male,Computer Science,Raj Patel

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 50 non-null     str
 1   Income             50 non-null     int64
 2   Student Loan Debt  50 non-null     int64
dtypes: int64(2), str(1)
memory usage: 1.3 KB

None

                                     ID  Income  Student Loan Debt
0  8f9158c3-1496-422d-b7d4-9a2917036850   69117              46874
1  4e43daa8-3428-46be-a58f-63c1f7a0b630   96540              44909
2  c18438e9-28b0-40fa-a7fb-ac978e8289b2   56071              15016
3  dba2fa25-af64-480e-afa3-3ba82ec38f9e   79009              15587
4  6d8393b6-e937-4889-b40a-ebcfa521db4f   99514               5037

In [4]:
# Now we will inspect if the 'ID' column in both datasets are same before we merge
print(alumni_data['id'].head())
print(income_debt_data['ID'].head())

# Check if both datasets are the same
(alumni_data['id'] == income_debt_data['ID']).all()

0    8f9158c3-1496-422d-b7d4-9a2917036850
1    4e43daa8-3428-46be-a58f-63c1f7a0b630
2    c18438e9-28b0-40fa-a7fb-ac978e8289b2
3    dba2fa25-af64-480e-afa3-3ba82ec38f9e
4    6d8393b6-e937-4889-b40a-ebcfa521db4f
Name: id, dtype: str
0    8f9158c3-1496-422d-b7d4-9a2917036850
1    4e43daa8-3428-46be-a58f-63c1f7a0b630
2    c18438e9-28b0-40fa-a7fb-ac978e8289b2
3    dba2fa25-af64-480e-afa3-3ba82ec38f9e
4    6d8393b6-e937-4889-b40a-ebcfa521db4f
Name: ID, dtype: str

np.True_

In [5]:
# Now that we know that both IDs are identical, we can merge
merged_data = pd.merge(alumni_data,
              income_debt_data,
              left_on="id",
              right_on="ID")

In [6]:
# Now we remove ID that is duplicate from the dataset
merged_data.drop(columns=["id"], inplace=True)

merged_data.info()
merged_data.head()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   age                50 non-null     int64
 1   gender             50 non-null     str
 2   major              50 non-null     str
 3   name               50 non-null     str
 4   ID                 50 non-null     str
 5   Income             50 non-null     int64
 6   Student Loan Debt  50 non-null     int64
dtypes: int64(3), str(4)
memory usage: 2.9 KB

,age,gender,major,name,ID,Income,Student Loan Debt
0,23,male,Psychology,James Whitaker,8f9158c3-1496-422d-b7d4-9a2917036850,69117,46874
1,26,male,Mathematics,Daniel Okafor,4e43daa8-3428-46be-a58f-63c1f7a0b630,96540,44909
2,24,male,Psychology,Marcus Delgado,c18438e9-28b0-40fa-a7fb-ac978e8289b2,56071,15016
3,30,male,Engineering,Ethan Brooks,dba2fa25-af64-480e-afa3-3ba82ec38f9e,79009,15587
4,28,male,Computer Science,Raj Patel,6d8393b6-e937-4889-b40a-ebcfa521db4f,99514,5037

In [7]:
# Analysis 1, demographics - average age by major and gender with percentage
average_age_by_major = merged_data.groupby("major")["age"].mean()
average_age_by_major = average_age_by_major.round(2)
print("Average Age by Major:")
display(average_age_by_major)

# Now we will convert the count into percentages
gender_percent_by_major = (merged_data.groupby("major")["gender"].value_counts(normalize=True) * 100)
gender_percent_by_major = gender_percent_by_major.round(2)
print("Gender Percentage by Major:")
display(gender_percent_by_major)

Average Age by Major:

major
Biology             24.50
Computer Science    25.75
Engineering         26.00
Mathematics         24.71
Physics             28.00
Psychology          25.69
Sociology           27.57
Name: age, dtype: float64

Gender Percentage by Major:

major             gender
Biology           male      50.00
                  female    50.00
Computer Science  male      50.00
                  female    50.00
Engineering       male      50.00
                  female    50.00
Mathematics       male      85.71
                  female    14.29
Physics           male      57.14
                  female    42.86
Psychology        male      76.92
                  female    23.08
Sociology         female    57.14
                  male      42.86
Name: proportion, dtype: float64

In [8]:
# Analysis 2
# Now we calculate the average income by major
average_income_by_major = (
    merged_data.groupby("major")["Income"]
        .mean().sort_values(ascending=False))
print("Average Income by Major:")

# Now we will use fstrings concept to organize the numbers
for major in average_income_by_major.index:
    print(major, f"${average_income_by_major[major]:,.2f}")

Average Income by Major:
Computer Science $94,360.75
Sociology $76,741.86
Mathematics $75,315.86
Biology $74,835.75
Psychology $67,053.92
Engineering $63,320.38
Physics $53,857.86

In [9]:
# Analysis 3
# Now we are calculating average debt by major
average_debt_by_major = (
    merged_data.groupby("major")["Student Loan Debt"]
        .mean().sort_values())
print("Average Debt by Major:")

# Now we will clean the debt numbers using fstring
for major in average_debt_by_major.index:
    print(major, f"${average_debt_by_major[major]:,.2f}")

Average Debt by Major:
Biology $17,557.00
Sociology $19,123.71
Computer Science $24,185.50
Mathematics $24,592.86
Physics $26,027.86
Engineering $26,642.88
Psychology $28,301.92

In [10]:
# Analysis 4
# Calculate how long will it take for each student to pay off their loan
monthly_income = merged_data["Income"] / 12
monthly_payment = monthly_income * 0.08
months_to_payoff = merged_data["Student Loan Debt"] / monthly_payment

# Now we will convert the months into years
years_to_payoff = months_to_payoff / 12
# Clean the numbers to one decimal point
years_to_payoff = years_to_payoff.round(1)

# We will add this as a new column to the main dataframe
merged_data["Years to Payoff"] = years_to_payoff

# Display only the relevant columns for loan payoff analysis
merged_data[["name", "major", "Income", "Student Loan Debt", "Years to Payoff"]]

,name,major,Income,Student Loan Debt,Years to Payoff
0,James Whitaker,Psychology,69117,46874,8.5
1,Daniel Okafor,Mathematics,96540,44909,5.8
2,Marcus Delgado,Psychology,56071,15016,3.3
3,Ethan Brooks,Engineering,79009,15587,2.5
4,Raj Patel,Computer Science,99514,5037,0.6
5,Lucas Moreau,Mathematics,72487,37021,6.4
6,Tyler Nguyen,Engineering,32552,12331,4.7
7,Sophia Ramirez,Mathematics,77576,25153,4.1
8,Hannah Kowalski,Sociology,61385,8796,1.8
9,Benjamin Cho,Psychology,61571,42182,8.6
10,Olivia Bennett,Physics,40322,10613,3.3
11,Jacob Fitzgerald,Sociology,93699,9535,1.3
12,Andre Thompson,Computer Science,99822,13241,1.7
13,Samuel Ortega,Physics,46828,48237,12.9
14,Priya Venkatesan,Sociology,92296,41031,5.6
15,Emily Hartman,Engineering,51643,22370,5.4
16,Chloe Washington,Computer Science,99163,44753,5.6
17,Natalie Sorensen,Sociology,85461,18880,2.8
18,Victor Alvarez,Psychology,56365,25428,5.6
19,Nathan Gallagher,Psychology,82296,49019,7.4
20,Isabella Romano,Computer Science,78944,33711,5.3
21,Kevin Yamamoto,Biology,97839,34588,4.4
22,Grace Lindqvist,Psychology,45860,21246,5.8
23,Owen Callahan,Physics,59451,9196,1.9
24,Hassan Rahimi,Psychology,74313,6378,1.1
25,Caleb Merritt,Engineering,60161,43564,9.1
26,Dylan Pruitt,Mathematics,58864,5471,1.2
27,Maya Srinivasan,Physics,39305,46359,14.7
28,Isaac Goldberg,Psychology,37716,20003,6.6
29,Trevor Landry,Mathematics,38834,7058,2.3
30,Zoe Calloway,Biology,73309,9643,1.6
31,Gabriel Santos,Mathematics,97391,20597,2.6
32,Mitchell Dunn,Psychology,66500,48842,9.2
33,Amara Johnson,Psychology,93624,19040,2.5
34,Leo Zhang,Physics,47342,42423,11.2
35,Austin Pereira,Psychology,91953,20925,2.8
36,Rachel Abernathy,Psychology,91993,31677,4.3
37,Alycia Rajendran,Physics,54957,11181,2.5
38,Jonathan Kim,Engineering,42704,48187,14.1
39,Elijah Montgomery,Sociology,86498,28219,4.1
40,Connor Vasquez,Mathematics,85519,31941,4.7
41,Aaliyah Coleman,Engineering,91213,8550,1.2
42,Megan Torres,Biology,42899,8972,2.6
43,Katherine Ellison,Engineering,82772,27236,4.1
44,Parker Lowell,Psychology,44322,21295,6.0
45,Fatima Haddad,Sociology,55112,17465,4.0
46,Julian Reyes,Physics,88800,14186,2.0
47,Wesley Tran,Biology,85296,17025,2.5
48,Brianna Hoang,Engineering,66509,35318,6.6
49,Patrick Doyle,Sociology,62742,9940,2.0

In [ ]:
# User menu for selecting an analysis
# First we will show the user all the available menu options
print("Alumni Research Analysis")
while True:
    print("1. Demographics")
    print("2. Income by Major")
    print("3. Debt by Major")
    print("4. Loan Pay-off in Years")
    
    # we will create a range of True and False conditions, to make sure the user will select the correct option
    try:
        choice = int(input("Enter your selection (1-4): "))
        if choice < 1 or choice > 4:
            print("Invalid entry, Please enter a number from 1 to 4.")
            continue
    except ValueError:
        print("Invalid entry. Please enter a number from 1 to 4.")
        continue
        
    # Now we will make sure that whatever option user selects, that it performs accurately
    if choice == 1:
        average_age_by_major = average_age_by_major.round(1)
        print("Demographics - Average Age by each Major")
        display(average_age_by_major)
        print("Male and Female percentage in each Major")
        display(gender_percent_by_major)

    elif choice == 2:
        print("Average Income by Major")
        for major in average_income_by_major.index:
            print(major,
                  f"${average_income_by_major[major]:,.2f}")

    elif choice == 3:
        print("Average Debt by Major")
        for major in average_debt_by_major.index:
            print(major,
                  f"${average_debt_by_major[major]:,.2f}")

    elif choice == 4:
        print("Years to Payoff Debt, 8% of income to debt payment")
        # we will show all the relevant columns for analysis 4
        display(
            merged_data[["name", "age", "major", "Income", "Student Loan Debt", 
                         "Years to Payoff"]])

Alumni Research Analysis
1. Demographics
2. Income by Major
3. Debt by Major
4. Loan Pay-off in Years

Enter your selection (1-4):  1

Demographics - Average Age by each Major

major
Biology             24.5
Computer Science    25.8
Engineering         26.0
Mathematics         24.7
Physics             28.0
Psychology          25.7
Sociology           27.6
Name: age, dtype: float64

Male and Female percentage in each Major

major             gender
Biology           male      50.00
                  female    50.00
Computer Science  male      50.00
                  female    50.00
Engineering       male      50.00
                  female    50.00
Mathematics       male      85.71
                  female    14.29
Physics           male      57.14
                  female    42.86
Psychology        male      76.92
                  female    23.08
Sociology         female    57.14
                  male      42.86
Name: proportion, dtype: float64

1. Demographics
2. Income by Major
3. Debt by Major
4. Loan Pay-off in Years

Enter your selection (1-4):  3

Average Debt by Major
Biology $17,557.00
Sociology $19,123.71
Computer Science $24,185.50
Mathematics $24,592.86
Physics $26,027.86
Engineering $26,642.88
Psychology $28,301.92
1. Demographics
2. Income by Major
3. Debt by Major
4. Loan Pay-off in Years

Enter your selection (1-4):  4

Years to Payoff Debt, 8% of income to debt payment

,name,age,major,Income,Student Loan Debt,Years to Payoff
0,James Whitaker,23,Psychology,69117,46874,8.5
1,Daniel Okafor,26,Mathematics,96540,44909,5.8
2,Marcus Delgado,24,Psychology,56071,15016,3.3
3,Ethan Brooks,30,Engineering,79009,15587,2.5
4,Raj Patel,28,Computer Science,99514,5037,0.6
5,Lucas Moreau,23,Mathematics,72487,37021,6.4
6,Tyler Nguyen,30,Engineering,32552,12331,4.7
7,Sophia Ramirez,25,Mathematics,77576,25153,4.1
8,Hannah Kowalski,29,Sociology,61385,8796,1.8
9,Benjamin Cho,22,Psychology,61571,42182,8.6
10,Olivia Bennett,28,Physics,40322,10613,3.3
11,Jacob Fitzgerald,24,Sociology,93699,9535,1.3
12,Andre Thompson,27,Computer Science,99822,13241,1.7
13,Samuel Ortega,28,Physics,46828,48237,12.9
14,Priya Venkatesan,27,Sociology,92296,41031,5.6
15,Emily Hartman,22,Engineering,51643,22370,5.4
16,Chloe Washington,23,Computer Science,99163,44753,5.6
17,Natalie Sorensen,30,Sociology,85461,18880,2.8
18,Victor Alvarez,27,Psychology,56365,25428,5.6
19,Nathan Gallagher,23,Psychology,82296,49019,7.4
20,Isabella Romano,25,Computer Science,78944,33711,5.3
21,Kevin Yamamoto,25,Biology,97839,34588,4.4
22,Grace Lindqvist,26,Psychology,45860,21246,5.8
23,Owen Callahan,27,Physics,59451,9196,1.9
24,Hassan Rahimi,27,Psychology,74313,6378,1.1
25,Caleb Merritt,26,Engineering,60161,43564,9.1
26,Dylan Pruitt,24,Mathematics,58864,5471,1.2
27,Maya Srinivasan,29,Physics,39305,46359,14.7
28,Isaac Goldberg,30,Psychology,37716,20003,6.6
29,Trevor Landry,27,Mathematics,38834,7058,2.3
30,Zoe Calloway,22,Biology,73309,9643,1.6
31,Gabriel Santos,26,Mathematics,97391,20597,2.6
32,Mitchell Dunn,27,Psychology,66500,48842,9.2
33,Amara Johnson,29,Psychology,93624,19040,2.5
34,Leo Zhang,29,Physics,47342,42423,11.2
35,Austin Pereira,24,Psychology,91953,20925,2.8
36,Rachel Abernathy,30,Psychology,91993,31677,4.3
37,Alycia Rajendran,28,Physics,54957,11181,2.5
38,Jonathan Kim,25,Engineering,42704,48187,14.1
39,Elijah Montgomery,29,Sociology,86498,28219,4.1
40,Connor Vasquez,22,Mathematics,85519,31941,4.7
41,Aaliyah Coleman,24,Engineering,91213,8550,1.2
42,Megan Torres,23,Biology,42899,8972,2.6
43,Katherine Ellison,29,Engineering,82772,27236,4.1
44,Parker Lowell,22,Psychology,44322,21295,6.0
45,Fatima Haddad,30,Sociology,55112,17465,4.0
46,Julian Reyes,27,Physics,88800,14186,2.0
47,Wesley Tran,28,Biology,85296,17025,2.5
48,Brianna Hoang,22,Engineering,66509,35318,6.6
49,Patrick Doyle,24,Sociology,62742,9940,2.0

1. Demographics
2. Income by Major
3. Debt by Major
4. Loan Pay-off in Years